---
# Defines tasks for RedHat/CentOS installation

- name: Set the system timezone
  template: >
    src=clock.j2
    dest=/etc/sysconfig/clock
    mode=0644 owner=root group=root
  tags:
    - timezone
